### PR TITLE
AzureNative V2

### PR DESCRIPTION
**Pull request by mvsmal**
This is the first work on AzureNative V2.
The generation works fine. Tested on a few services in a real-world project.

A few important notes:
* I extracted `NamingConventions` and `Locations` to a common project referenced by both AzureNative and AzureNativeV2 to avoid code duplication
* I left the resulting namespace as is: `Pulumi.FSharp.AzureNative`. Firstly, because it will be easier to migrate to the new version in the existing projects and secondly because otherwise we would need to introduce more parameters in the `createModules` function. Here: [IndexModule.fs#L125-L126](https://github.com/UnoSD/Pulumi.FSharp.Extensions/blob/master/Pulumi.FSharp.Myriad/IndexModule.fs#L125-L126) the `provider` argument is used in both module declaration and `open` statement.

Please have a look and let me know if see any issues.

### CODE REVIEW

**Comment by UnoSD** [comment]
@mvsmal were you able to build the AzureNativeV2? I am getting the following error:

```
$ dotnet fake run build.fsx AzureNativeV2

Script reported an error:
-> BuildFailedException: Target 'Pack' failed.
   StackTrace:
        at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 991
        at Fake.Core.TargetModule.runOrDefaultWithArguments(String defaultTarget) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 1177
        at <StartupCode$build_6BFBA565A00900959DCFDFA89576CD74E6252979C94798502681092BA20BE1E3>.$Build$fsx.main@() in /home/uno/savs/sourcecode/dotNET/Pulumi.FSharp.Extensions/build.fsx:line 278
-> One or more errors occurred. (XML node '/Project/ItemGroup/PackageReference[@Include='Pulumi.AzureNativeV2']' not found)
-> XML node '/Project/ItemGroup/PackageReference[@Include='Pulumi.AzureNativeV2']' not found
   StackTrace:
        at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
        at Build.clo@188-13.Invoke(String provider) in /home/uno/savs/sourcecode/dotNET/Pulumi.FSharp.Extensions/build.fsx:line 216
        at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 497
        at Build.clo@185-12.Invoke(TargetParameter _arg6) in /home/uno/savs/sourcecode/dotNET/Pulumi.FSharp.Extensions/build.fsx:line 186
        at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 300
```

**Comment by mvsmal** [comment]
Hi @UnoSD. Yes, sorry, we need an override there. I didn't commit it. I will submit a PR shortly. But maybe you will have a better idea

**Comment by mvsmal** [comment]
@UnoSD Here you go: https://github.com/UnoSD/Pulumi.FSharp.Extensions/pull/26

**Comment by UnoSD** [comment]
thank you @mvsmal

**Comment by mvsmal** [comment]
Hi @UnoSD. Could you please release AzureNativeV2 package? We already need it in our project. It turns out, even the latest v1 is missing some APIs.

**Comment by UnoSD** [comment]
hi @mvsmal, I have built and published the NuGet package: https://www.nuget.org/packages/Pulumi.FSharp.AzureNativeV2/2.15.0.2

let me know if that works

**Comment by mvsmal** [comment]
@UnoSD yes, it works fine. Thanks a lot

**Pull request merged**
